In [6]:
import string
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
#Load the data from https://www.kaggle.com/datasets/venky73/spam-mails-dataset
df = pd.read_csv('spam_ham_dataset.csv')
print(df.head(5)) 
df.head(5);

#Print the shape of the df
print(df.shape)

#Get columnnames
print(df.columns)

#Check for duplicates
df.drop_duplicates(inplace = True)
print(df.shape)

#Show number of missign (NAN, NAN, na) data for each colum
print(df.isnull().sum()) 

#Download the stopwords
def process_text(text): 
    #1 remove punctuation
    #2 remove stopwords
    #3 return list of clean text words

    nopunc = [char for char in text if char not in string.punctuation] 
    nopunc = ''.join(nopunc) 
    
    #returns csv without punction
    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

    return clean_words


   Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0  
(5171, 4)
Index(['Unnamed: 0', 'label', 'text', 'label_num'], dtype='object')
(5171, 4)
Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64


In [5]:

#Tokenization - seperate words by comma 
print(df['text'].head(6).apply(process_text))
df2['Body'].head(6).apply(process_text)


0    [Subject, enron, methanol, meter, 988291, foll...
1    [Subject, hpl, nom, january, 9, 2001, see, att...
2    [Subject, neon, retreat, ho, ho, ho, around, w...
3    [Subject, photoshop, windows, office, cheap, m...
4    [Subject, indian, springs, deal, book, teco, p...
5    [Subject, ehronline, web, address, change, mes...
Name: text, dtype: object


NameError: name 'df2' is not defined

In [6]:
df.columns

Index(['Unnamed: 0', 'label', 'text', 'label_num'], dtype='object')

In [7]:
message4 = 'hello word hello hello'
message5 = 'test etstst tests one hello'
print(message4)
print

#Convert text to matrix of tokens counts
from sklearn.feature_extraction.text import CountVectorizer
bow4 = CountVectorizer(analyzer=process_text).fit_transform([[message4], [message5]])
print(bow4)

print(bow4.shape) #unique words


hello word hello hello
  (0, 1)	3
  (0, 5)	1
  (1, 1)	1
  (1, 3)	1
  (1, 0)	1
  (1, 4)	1
  (1, 2)	1
(2, 6)


In [2]:
#Convert collection of text to a matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer
message_bow = CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [7]:
#Split data into 80% traisning and 20% testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(message_bow, df['label_num'], test_size=0.20, random_state= 0)

In [8]:
#Get the shape of messages_bow
message_bow.shape

(5171, 50381)

In [9]:
#Create and train the Naive Bayes Classifer
from sklearn.naive_bayes import MultinomialNB
classifer = MultinomialNB().fit(X_train, Y_train)

In [ ]:

print(class)

In [11]:
print(classifer.predict(X_train))

print(Y_train.values)

emails=[
    'Sounds great! Are you home now?',
    'Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES'
]

classifer.predict(emails)

[0 0 0 ... 1 0 0]
[0 0 0 ... 1 0 0]


ValueError: Expected 2D array, got 1D array instead:
array=['Sounds great! Are you home now?'
 'Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [36]:
#Evalute the model on the training data
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifer.predict(X_train)
print(classification_report(Y_train, pred))
print()
print('Confusion MAtrix: ')
print(confusion_matrix(Y_train, pred))
print
print("Accuracy: ")
print(accuracy_score(Y_train, pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      2940
           1       0.98      0.97      0.98      1196

    accuracy                           0.99      4136
   macro avg       0.99      0.98      0.98      4136
weighted avg       0.99      0.99      0.99      4136


Confusion MAtrix: 
[[2918   22]
 [  30 1166]]
Accuracy: 
0.9874274661508704


In [37]:
print(classifer.predict(X_test))

print(Y_test.values)

[0 0 0 ... 0 1 0]
[0 0 0 ... 0 1 0]


In [38]:
pred = classifer.predict(X_test)
print(classification_report(Y_test, pred))
print()
print('Confusion MAtrix: ')
print(confusion_matrix(Y_test, pred))
print
print("Accuracy: ")
print(accuracy_score(Y_test, pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       732
           1       0.95      0.96      0.96       303

    accuracy                           0.97      1035
   macro avg       0.97      0.97      0.97      1035
weighted avg       0.97      0.97      0.97      1035


Confusion MAtrix: 
[[718  14]
 [ 13 290]]
Accuracy: 
0.9739130434782609


In [22]:
data = pd.read_csv('spam_ham_dataset.csv')
data

Unnamed: 0 label                                               text  \
0            605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1           2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2           3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3           4685  spam  Subject: photoshop , windows , office . cheap ...   
4           2030   ham  Subject: re : indian springs\r\nthis deal is t...   
...          ...   ...                                                ...   
5166        1518   ham  Subject: put the 10 on the ft\r\nthe transport...   
5167         404   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...   
5168        2933   ham  Subject: calpine daily gas nomination\r\n>\r\n...   
5169        1409   ham  Subject: industrial worksheets for august 2000...   
5170        4807  spam  Subject: important online banking alert\r\ndea...   

      label_num  
0             0  
1             0  
2             0  
3             1  
4             0  
...         ...  
5166          0  
5167          0  
5168          0  
5169          0  
5170          1  

[5171 rows x 4 columns]

In [23]:
X_train,X_test,y_train,y_test=train_test_split(data.text,data.label_num,test_size=0.25)

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

In [25]:
from sklearn.naive_bayes import MultinomialNB

In [26]:
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [27]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [31]:
emails=[
    'Sounds great! Are you home now?',
    'Will u meet urerereeererer dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES',
    'photoshop , windows , office . cheap'

]

clf.predict(emails)

array([1, 1, 1], dtype=int64)

In [29]:
clf.score(X_test,y_test)

0.9698375870069605